In [5]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['NAME'], axis=1)
application_df.head()

,EIN,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#USING SMALLER NUMBER FOR 1st optimization round
application_types_to_replace = list(application_counts[application_counts<50].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
Other       54
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# USING SMALLER NUMBER FOR OPTIMIZATION attempt 1, ATTEMPT 2, lowering number again
classifications_to_replace = list(classification_counts[classification_counts < 50].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      391
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: count, dtype: int64

In [11]:
X_encoded = pd.get_dummies(application_df, dtype=int)
X_encoded

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,10531628,1,108590,1,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,1,0
2,10547893,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,10553066,1,6692,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,10556103,1,142590,1,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,1,5000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34295,996010315,1,5000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34296,996012607,1,5000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34297,996015768,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,996086871,1,36500179,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0

In [27]:
# Split our preprocessed data into our features and target arrays
y = X_encoded["IS_SUCCESSFUL"]
X = X_encoded.drop(columns=["IS_SUCCESSFUL"])
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

In [28]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [29]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
## ADDING MORE NEURONS AND ADDITIONAL LAYER FOR OPTIMIZATION, also changed activation
## THIRD OPTIMIZATION INCREASED NEURONS, switched all activations

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=100,activation='relu',input_dim=56))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=100,activation='swish'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=50,activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 100)               5700

 dense_13 (Dense)            (None, 100)               10100

 dense_14 (Dense)            (None, 50)                5050

 dense_15 (Dense)            (None, 1)                 51

=================================================================
Total params: 20901 (81.64 KB)
Trainable params: 20901 (81.64 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [30]:
# Compile the model
nn.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
# Train the model # USING LESS EPOCHS TO CUT DOWN ON TIME
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5658 - accuracy: 0.7220
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7303
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7319
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7337
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5419 - accuracy: 0.7362
Epoch 6/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5404 - accuracy: 0.7348
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7364
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7364
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7374
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7388
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5330 - accuracy: 0.7411
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7403
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7430
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7421
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7437
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7428
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5271 - accuracy: 0.7445
Epoch 19/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5264 - accuracy: 0.7449
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7460
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5243 - accuracy: 0.7463
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5232 - accuracy: 0.7471
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5217 - accuracy: 0.7466
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5216 - accuracy: 0.7476
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5208 - accuracy: 0.7474
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5195 - accuracy: 0.7481
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5196 - accuracy: 0.7479
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5191 - accuracy: 0.7479
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5174 - accuracy: 0.7500
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5170 - accuracy: 0.7500
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5168 - accuracy: 0.7499
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5163 - accuracy: 0.7512
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5152 - accuracy: 0.7508
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5145 - accuracy: 0.7499
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5141 - accuracy: 0.7509
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5136 - accuracy: 0.7514
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5125 - accuracy: 0.7524
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5127 - accuracy: 0.7505
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5121 - accuracy: 0.7510
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5109 - accuracy: 0.7531
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5108 - accuracy: 0.7528
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5103 - accuracy: 0.7515
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5096 - accuracy: 0.7528
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5088 - accuracy: 0.7533
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5089 - accuracy: 0.7536
Epoch 46/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5078 - accuracy: 0.7528
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5076 - accuracy: 0.7548
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5076 - accuracy: 0.7533
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5071 - accuracy: 0.7549
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5061 - accuracy: 0.7533
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5058 - accuracy: 0.7558
Epoch 52/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5055 - accuracy: 0.7567
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5065 - accuracy: 0.7550
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5038 - accuracy: 0.7581
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5040 - accuracy: 0.7550
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5036 - accuracy: 0.7563
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5036 - accuracy: 0.7551
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5027 - accuracy: 0.7563
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5027 - accuracy: 0.7565
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5018 - accuracy: 0.7559
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5020 - accuracy: 0.7576
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5025 - accuracy: 0.7563
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5013 - accuracy: 0.7578
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5010 - accuracy: 0.7568
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5015 - accuracy: 0.7563
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5002 - accuracy: 0.7568
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5003 - accuracy: 0.7573
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4994 - accuracy: 0.7580
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4988 - accuracy: 0.7573
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4987 - accuracy: 0.7586
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4988 - accuracy: 0.7570
Epoch 72/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4990 - accuracy: 0.7577
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4980 - accuracy: 0.7575
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4977 - accuracy: 0.7586
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4973 - accuracy: 0.7585
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4968 - accuracy: 0.7578
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4974 - accuracy: 0.7585
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4967 - accuracy: 0.7584
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4967 - accuracy: 0.7589
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4965 - accuracy: 0.7577
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4962 - accuracy: 0.7582
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4951 - accuracy: 0.7602
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4951 - accuracy: 0.7591
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4948 - accuracy: 0.7590
Epoch 85/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4948 - accuracy: 0.7611
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4946 - accuracy: 0.7600
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4946 - accuracy: 0.7594
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4935 - accuracy: 0.7605
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4941 - accuracy: 0.7594
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4931 - accuracy: 0.7608
Epoch 91/100
419/804 [==============>...............] - ETA: 0s - loss: 0.4900 - accuracy: 0.7650

In [32]:
# Evaluate the model using the test data
# FIRST OPTIMIZATION ACCURACY = .7308
# SECOND OPTIMIZATION ACCURACY = .7329
# THIRD OPTIMIZATION ACCURACY = .7322
# FOURTH OPTIMIZATION ACCURACY = .7300
 # FIFTH OPTIMIZATION ACCURACY = .7297
 #FIFTH/ dropped additional columns, added more neurons and readjusted activation
 #6th optimization dropped NAME and kept EIN
 # SIXTH OPTIMIZTION ACCURACY = .7335, it did get up to .76 by the last epoch
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5906 - accuracy: 0.7301 - 499ms/epoch - 2ms/step
Loss: 0.5905593037605286, Accuracy: 0.7301457524299622

In [33]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(